# Generated by Django 5.0.1 on 2024-01-25 09:55

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='background',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.background', verbose_name='background'),
        ),
        migrations.AddField(
            model_name='node',
            name='links',
            field=models.ManyToManyField(to='characters.node', verbose_name='links'),
        ),
        migrations.AlterField(
            model_name='node',
            name='bonus_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('STA', 'Stamina'), ('QUI', 'Quickness'), ('RES', 'Resistance'), ('INT', 'Intelligence'), ('CHA', 'Charisma'), ('WIL', 'Will'), ('POW', 'Power')]), blank=True, default=list, size=9),
        ),
        migrations.AlterField(
            model_name='node',
            name='position_x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='position_x'),
        ),
        migrations.AlterField(
            model_name='node',
            name='position_y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)], verbose_name='position_y'),
        ),
    ]
