# Generated by Django 5.0.1 on 2024-01-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_node_background_node_links_alter_node_bonus_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='height',
            field=models.IntegerField(default=150, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='board',
            name='width',
            field=models.IntegerField(default=200, verbose_name='width'),
        ),
        migrations.AddField(
            model_name='node',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image_name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='boards',
            field=models.ManyToManyField(blank=True, to='characters.board', verbose_name='notable'),
        ),
        migrations.AlterField(
            model_name='character',
            name='improvements',
            field=models.ManyToManyField(blank=True, to='characters.improvement', verbose_name='improvements'),
        ),
        migrations.AlterField(
            model_name='character',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='characters.node', verbose_name='notable'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_expertises',
            field=models.ManyToManyField(blank=True, to='characters.skill', verbose_name='skill_expertises'),
        ),
        migrations.AlterField(
            model_name='character',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='characters.speciality', verbose_name='specialities'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spell_expertises',
            field=models.ManyToManyField(blank=True, to='characters.spell', verbose_name='spell_expertises'),
        ),
        migrations.AlterField(
            model_name='node',
            name='links',
            field=models.ManyToManyField(blank=True, to='characters.node', verbose_name='links'),
        ),
    ]
